# Generated by Django 4.2.9 on 2024-01-07 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aireadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('username', models.CharField(db_index=True, help_text='用户账号', max_length=150, unique=True, verbose_name='用户账号')),
                ('apikey', models.CharField(db_index=True, help_text='APIKey', max_length=127, unique=True, verbose_name='APIKey')),
                ('num_usable', models.IntegerField(default=100, help_text='剩余可调用次数', verbose_name='剩余可调用次数')),
                ('num_day_usable', models.IntegerField(default=100, help_text='今日可调用次数', verbose_name='今日可调用次数')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('invoke_time', models.DateTimeField(auto_now_add=True, help_text='最近调用时间', verbose_name='最近调用时间')),
            ],
            options={
                'verbose_name': 'APIKey',
                'verbose_name_plural': 'APIKey',
                'db_table': 'aire_system_apikey',
                'ordering': ['-create_time'],
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
